name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Routine
        uses: dogu-team/dogu-github-action@v1.0
        with:
          project-id: 'fb2b1e15-e828-46f1-894a-9e58aa3313dd'
          routine-id: 'a22a7b3a-59f7-4a86-b5cf-dac990e322a7'
          api-url: https://api.dev.dogutech.io
        env:
          DOGU_TOKEN: ${{ secrets.DOGU_PROJECT_TOKEN }}
